services:
  dev-erlang:
    build:
      dockerfile: Dockerfile.deverlang
    env_file:
      - .env
    volumes:
      - .:/src/sybil
    networks:
      static-network:
        ipv4_address: 172.20.128.101
  dev-inspector:
    build:
      dockerfile: Dockerfile.devinspector
    networks:
      static-network:
        ipv4_address: 172.20.128.100
  herd-memory:
    image: localhost/herdmate
    env_file:
      - .env
    volumes:
      - ./ollama:/root/.ollama
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    devices:
      - nvidia.com/gpu=all
  herd-feels:
    image: localhost/herdmate
    env_file:
      - .env
    volumes:
      - ./ollama:/root/.ollama
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    devices:
      - nvidia.com/gpu=all
  herd-collector:
    image: localhost/herdmate
    env_file:
      - .env
    volumes:
      - ./ollama:/root/.ollama
    networks:
      static-network:
        ipv4_address: 172.20.128.4
    devices:
      - nvidia.com/gpu=all
  herd-morals:
    image: localhost/herdmate
    env_file:
      - .env
    volumes:
      - ./ollama:/root/.ollama
    networks:
      static-network:
        ipv4_address: 172.20.128.5
    devices:
      - nvidia.com/gpu=all
  herd-coder:
    image: localhost/herdmate
    env_file:
      - .env
    volumes:
      - ./ollama:/root/.ollama
    networks:
      static-network:
        ipv4_address: 172.20.128.6
    devices:
      - nvidia.com/gpu=all
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
