# stage 1
FROM ubuntu AS base

EXPOSE 11434
WORKDIR /

# stage 2
FROM base as ollama

# install ollama
RUN apt update
RUN apt upgrade -y
RUN apt install screen curl -y
RUN curl -fsSL https://ollama.com/install.sh | sh

# stage 3
FROM ollama AS herdmate
ENV OLLAMA_HOST=0.0.0.0
